name: Sync Upstream
on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次（可调整）
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Fork
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.repos.mergeUpstream({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'master'
              });
              console.log('Sync successful!');
            } catch (error) {
              console.error('Sync failed:', error);
            }
